module.exports = {
    'GSHEETS': {
        "SUBMIT_FORM_SUBMITTING" : "GSHEETS:SUBMIT_FORM_SUBMITTING",
        "SUBMIT_FORM_SUCCESS"    : "GSHEETS:SUBMIT_FORM_SUCCESS",
        "SUBMIT_FORM_FAILURE"    : "GSHEETS:SUBMIT_FORM_FAILURE"
    }
};
